### ISSUE TITLE
node_modules文件数量几万个 压缩很慢 低配置机器甚至会内存溢出、死机等

### ISSUE THREAD

**Issue by golezi** [serverless-components/tencent-express#17]
安装依赖只用几分钟，但是压缩打包时，node_modules/ 文件夹下的几万个文件对压缩很不友好
上传一个代码仅几M的项目却要同时上传几十M的依赖也很不合理
nodejs开发通常也都是部署时在服务器安装依赖而不会复制/node_modules 文件夹过去
但是在文档中好像没有看到由服务器安装依赖的选项
希望能给出一个合适的解决方案
如由serverless服务器解压用户上传的文件夹后自动执行npm i安装依赖
或者服务器预先配置好环境

**Comment by tinafangkunding** [comment]
收到您的反馈，这里正在优化，晚点同步一下详细的进展

**Comment by tinafangkunding** [comment]
hi 您好 @golezi 这边是讨论后的一些进展反馈：

1. node_modules大的问题，是比较通用的问题。主流的 FaaS 平台都会遇到，并且依赖较大时，不仅会遇到打包慢，上传慢的问题，在函数加载代码时也会遇到冷启动等情况。目前有三个计划的解决方案。
a. 通过layer component和 scf component 配合减少依赖的重复打包上传，甚至提供一些公用的 依赖layers ——预计月底支持
b. 支持 上传缓存，检测依赖中有变化才传，否则不会上传。不过对于大的依赖依然建议layer
c. 后续在考虑支持部署的过程中才安装依赖，但是也要看npm的安装速度。这个还在规划中

如果您有好的建议和反馈，欢迎继续提给我们

**Comment by hardForLucky** [comment]
### 执行serverless 时 报错
**参照《部署 Vue+Express 全栈应用》文档时，执行serverless遇到以下报错：**

@serverless\tencent-scf\node_modules\serverless-tencent-tools\sdk\debug\lib\wshub-client\index.js:88
var __spreadArrays =
^^^

SyntaxError: Unexpected token var
