### ISSUE TITLE
图片无法正常显示

### ISSUE THREAD

**Issue by bear-shchan** [serverless-components/tencent-express#19]
看aws的处理是，有写入一个binaryMimeTypes=['image/png']变量，请问下该components有提供相应的参数设置吗？

**Comment by tinafangkunding** [comment]
收到您的反馈， @yugasun  可以辛苦帮忙看一下这里的策略

**Comment by yugasun** [comment]
@serverless/tencent-express@3.0.3 已经支持该配置：https://github.com/serverless-components/tencent-express/releases/tag/v3.0.3
