### ISSUE TITLE
请问参数怎么填？How to fill in the parameters?

### ISSUE THREAD

**Issue by StiffFy** [serverless-components/tencent-express#2]
PS D:\serverless\demo> sls --debug

位于命令管道位置 1 的 cmdlet Select-String
请为以下参数提供值:
Path[0]:

**Comment by pmuens** [comment]
Hey @StiffFy thanks for opening :+1:

Could you share the `serverless.js` file, `serverless.yml` file or project setup you're using? You can find the list of parameters you can provider [here](https://github.com/serverless-components/tencent-express/blob/master/docs/configure.md).

**Comment by pmuens** [comment]
Closing this issue since it got stale. Feel free to re-open if this problem still persists.
