### ISSUE TITLE
执行serverless 时 报错

### ISSUE THREAD

**Issue by hardForLucky** [serverless-components/tencent-express#24]
**参照《部署 Vue+Express 全栈应用》文档时，执行serverless遇到以下报错：**

@serverless\tencent-scf\node_modules\serverless-tencent-tools\sdk\debug\lib\wshub-client\index.js:88
var __spreadArrays =
^^^

SyntaxError: Unexpected token var

**Comment by yugasun** [comment]
@hardForLucky 可以尝试更新下 `serverless` 命令：`npm install serverless -g`

**Comment by hardForLucky** [comment]
> @hardForLucky 可以尝试更新下 `serverless` 命令：`npm install serverless -g`

依然不行，先卸载掉再npm install serverless -g，重新执行serverless依然报错
npm: 6.4.1
node: v10.15.2

**Comment by yugasun** [comment]
可以提供下 `serverless` 版本号，执行 `serverless --version`:
```bash
$ serverless --version
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.2
```

如果跟以上版本不一致，`Framework Core: 1.67.2` 确实存在该问题，但是 `Framework Core: 1.67.3` 官方已经修复的。

**Comment by hardForLucky** [comment]
> serverless --version
版本与你的完全一致
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.2
完全一致。

**Comment by anycodes** [comment]
`npm update`看一下，应该是要把@serverless/compoment里面的node_modules->serverless-tencent-tools更新到最新版

**Comment by anycodes** [comment]
也可以新建一个项目，然后再试试。
同时也可以：
删除本项目的.serverless目录：`rm .serverless`，这里要注意，如果有tencent-cos组件慎重删除！
删除缓存目录：`rm -rf ~/.serverless/components/registry/npm/@serverless`

**Comment by hardForLucky** [comment]
依然不行，放弃了，又换了一个egg的示例好像也跑不起来 - - 尴尬。我换个地方提issues吧
