### ISSUE TITLE
req.ip is undefined

### ISSUE THREAD

**Issue by inu1255** [serverless-components/tencent-express#39]

**Comment by yugasun** [comment]
epress 组件在将 API 网关传递给云函数的 `event` 转化为 HTTP 请求后，会将 event 对象赋值给 `app.request.__SLS_EVENT__` 而 API 网关触发器的 event 中 `requestContext.sourceIp` 就是客户端请求 IP，因此我们可以在云函数的代码中获取这个属性，示例如下：

```js
app.get(`/ip`, (req, res) => {
  res.send({
    id: req.__SLS_EVENT__.requestContext.sourceIp
  })
})
```
