### ISSUE TITLE
An error in this component about `Socket hang up`

### ISSUE THREAD

**Issue by anycodes** [serverless-components/tencent-express#4]
An error in this component when I used it
<img width="1188" alt="企业微信截图_b2d24b94-5cec-4707-bb35-a941def791d7" src="https://user-images.githubusercontent.com/21079031/70676390-f784cf80-1cc6-11ea-8b20-903d2f8c8140.png">
I want to know the reason about it, what should I do.

**Comment by tinafangkunding** [comment]
cc @pmuens  please check this issue, thanks!

**Comment by pmuens** [comment]
> cc @pmuens please check this issue, thanks!

Sure. Looking into this...

**Comment by pmuens** [comment]
Hey @anycodes thanks for opening :+1:

Could you provide the `serverless.yml` / `serverless.js` file you've used? I tried to reproduce the problem on my end but wasn't able to do so. I'm using the following config:

```yaml
express:
  component: @serverless/tencent-express
  inputs:
    region: ap-shanghai
```
[Apparently your request is timing out](https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean).

Maybe we should queue the request and retry or gracefully exit with a more descriptive error message. Is there maybe a specific `serverless.yml` config we could use to enforce this kind or error? That way I could dig deeper into the internals.
