### ISSUE TITLE
The value of "value" is out of range. It must be >= 0 and <= 65535. Received 96564

### ISSUE THREAD

**Issue by athemeroy** [serverless-components/tencent-express#47]
我在执行 sls deploy 命令的时候，上传成功，提示deploying……  然后弹出这样一个错误
请问value这个字段是哪里来的？
不太知道应该怎么办呀

**Comment by yugasun** [comment]
@athemeroy 这个是 `node_modules` 文件过多导致的，部署前可以通过执行 `npm install --production` 来精简该文件夹。
