### ISSUE TITLE
返回多个cookie，只能获取到一个

### ISSUE THREAD

**Issue by GiantappMan** [serverless-components/tencent-express#6]
```
app.post("/testCookie", (req, res, next) => {
  res.cookie("test0", '000');
  res.cookie("test1", 111);
  res.send('Cookie is set');
});
```
本地测试：
![image](https://user-images.githubusercontent.com/80653/72142300-58d7b580-33cf-11ea-97dc-b7f235fd2202.png)

发布到serverless:
![image](https://user-images.githubusercontent.com/80653/72142318-61c88700-33cf-11ea-8142-8d0e9148eb51.png)

后台日志:
![image](https://user-images.githubusercontent.com/80653/72142349-6ee57600-33cf-11ea-90a0-c972ee39134c.png)

**Comment by GiantappMan** [comment]
https://github.com/DaZiYuan/test-serverless/tree/master/api
今天我又试了一下，确认重现

**Comment by tinafangkunding** [comment]
收到，感谢反馈。 辛苦 @anycodes @yugasun 帮忙看一下。

**Comment by yugasun** [comment]
@DaZiYuan 已经提交修复 PR https://github.com/serverless-components/tencent-express/pull/7 ，待官方合入后，就可以解决此问题。
